## matrice 4x5 casuale. sottrai da ogni colonna la sua media e dividi per la sua deviazione (np.std)


In [1]:
import numpy as np

In [35]:
matrix = np.random.uniform(0, 100,(4,5))
mediaColonne = np.sum(matrix, axis=0) / matrix.shape[1]
deviazione = np.std(matrix, axis=0)
mediaColonne / deviazione

array([1.21406045, 1.8705976 , 1.28155029, 1.2560632 , 1.86992001])

## matrice 6x6 interi casuali -10+10. sostituire i valori negativi con 0, 
## estrarre le righe che hanno somma maggiore di 15


In [34]:
matrix2 = np.random.randint(-10,10,(6,6))
matrix2[matrix2 < 0] = 0
sommaRighe = np.sum(matrix2, axis = 1)
matrix2[sommaRighe > 15] 
matrix2

array([[0, 1, 0, 0, 0, 0],
       [7, 1, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [6, 5, 1, 7, 0, 0],
       [8, 6, 3, 0, 2, 8],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

array 100 temperature tra -5 + 35. Trova quanti giorni hanno 15 < t < 25
sostituisci le t sotto 0 con 0 e sopra 30 con 30


In [58]:
matrix3 = np.random.randint(-5, 35, 100)
filtro = (matrix3 >= 15) & (matrix3 <= 25)
numGiorni = matrix3[filtro].size
print(numGiorni)
matrix3[matrix3 < 0] = 0
matrix3[matrix3 > 30] = 30
matrix3

32


array([ 6,  0, 21, 21, 27,  8,  0, 17,  0, 11,  6,  0, 30,  0,  0, 23,  8,
       30,  0, 18, 22,  6, 16, 13,  0, 26, 11,  4, 11, 13,  3, 21, 30,  1,
       16, 13, 30, 17, 26,  9, 28, 21, 22,  4,  0, 21, 30, 11,  9,  0, 17,
       22, 16,  6, 18, 26, 21, 22, 26, 12, 13, 18, 13,  6, 25, 26,  0,  0,
       22, 30, 16, 20, 13, 30, 18, 10,  8,  8, 17, 15,  0,  0, 22, 15, 14,
       23, 10,  8, 21,  0, 21, 11, 29, 26,  4, 30, 14,  4,  3, 28],
      dtype=int32)