# NumPy


Permette di scrivere codice python alla veloocità/prestazioni simili a C

Molte librerie hanno al loro interno NumPy

Librerie intelligenza artificiale hanno seguito stile NumPy:
    
- PyTorch
- Jax
- MLX

Nate perché PyTorch agiva solo su CPU mentre le altre anche sul GPU

In [2]:
import numpy as np

# Array in NumPy (`ndarray`)
array molto simili a C

In [3]:
#array di interi
array_int = np.zeros(5, dtype = np.int32)
array_int

array([0, 0, 0, 0, 0], dtype=int32)

In [4]:
array_float = np.zeros(5, dtype = np.float64)
array_float                       

array([0., 0., 0., 0., 0.])

In [6]:
array_complex = np.zeros(5, dtype = np.complex128)
array_complex

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [8]:
print(array_int.dtype)
print(array_float.dtype)
print(array_complex.dtype)

int32
float64
complex128


In [11]:
#Matrice di float
matrix_float = np.zeros((5,7), dtype = np.float64)
matrix_float

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [14]:
#Memoria occupata
print(array_int.nbytes)
#shape usata nelle matrici
print(array_int.shape)
print(matrix_float.shape)

20
(5,)
(5, 7)


matrix.shape ti restituisce una *tupla*, shape[0] = righe | shape[1] = colonne


In [22]:
#Broadcasting (aggiunge 1 a ogni elemento)
array_int_new = array_int + 1
print(array_int_new)
array_int_new = array_int + 1. #fa la conversione in float
print(array_int_new)
print(array_int_new.dtype)

[1 1 1 1 1]
[1. 1. 1. 1. 1.]
float64


In [26]:
v1 = np.array([1,2], dtype = np.int32)
print(v1)
v2 = np.array([3,-5])
print(v2)
print(v1 + v2)

[1 2]
[ 3 -5]
[ 4 -3]


In [33]:
# Uniform(a, b, shape) genera un array di dimensioni shape con valori pseudo casuale compresi tra a e b
array_random = np.random.uniform(0, 1, (100000000))
print(array_random)

[0.99279086 0.01418033 0.56741005 ... 0.2016484  0.93425035 0.71983471]


Numpy usa gli array come vettori e applica le regole dei vettori